-- ============================================================
-- PRE-DEPLOY — Run as PLATFORM_DEPLOY_ROLE before first DCM deploy
-- Creates objects that DCM cannot manage itself
-- ============================================================

USE ROLE PLATFORM_DEPLOY_ROLE;

-- Platform DCM project home
CREATE DATABASE IF NOT EXISTS PLATFORM_DCM;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DCM.PROJECTS;
CREATE DCM PROJECT IF NOT EXISTS PLATFORM_DCM.PROJECTS.PLATFORM_PROJECT;

-- Feature repo DCM project objects
CREATE DATABASE IF NOT EXISTS FITNESS_DCM;
CREATE SCHEMA IF NOT EXISTS FITNESS_DCM.PROJECTS;
CREATE DCM PROJECT IF NOT EXISTS FITNESS_DCM.PROJECTS.FITNESS_PROJECT_DEV;
CREATE DCM PROJECT IF NOT EXISTS FITNESS_DCM.PROJECTS.FITNESS_PROJECT_PROD;
