USE ROLE PLATFORM_DEPLOY_ROLE;

CREATE USER IF NOT EXISTS PLATFORM_DEPLOYER
    DEFAULT_ROLE      = 'PLATFORM_DEPLOY_ROLE'
    DEFAULT_WAREHOUSE = 'PLATFORM_DEPLOY_WH'
    TYPE = SERVICE
    COMMENT = 'Service account for platform-admin repo DCM deployments';

GRANT ROLE PLATFORM_DEPLOY_ROLE TO USER PLATFORM_DEPLOYER;
