USE ROLE PLATFORM_DEPLOY_ROLE;

CREATE USER IF NOT EXISTS DSOSINSKI_DEVELOPER
    DEFAULT_ROLE           = 'DEVELOPER_ROLE'
    TYPE                   = PERSON
    MUST_CHANGE_PASSWORD   = TRUE
    PASSWORD               = '__DEFAULT_USER_PASSWORD__'
    COMMENT                = 'Developer - DSosinski';

GRANT ROLE DEVELOPER_ROLE TO USER DSOSINSKI_DEVELOPER;

ALTER USER DSOSINSKI_DEVELOPER SET DISABLED = FALSE;
