name: Deploy Snowflake DCM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: "PLATFORM_DEPLOYER"
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: "SNOWFLAKE_JWT"
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PLATFORM_DEPLOYER_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          cli-version: "3.16.0"
          default-config-file-path: "config.toml"

      - name: Check Snowflake CLI version
        run: snow --version

      - name: Print config.toml
        run: cat ~/.snowflake/config.toml

      - name: Verify connection
        run: snow connection test 

      - name: Plan deployment
        run: snow dcm plan --target PLATFORM --connection myconnection

      - name: Deploy
        run: snow dcm deploy --target PLATFORM --connection myconnection
